import type { CategoryGroup, FieldSpec, FormStep } from "./types";
import { ALL_CATEGORY_GROUPS } from "./types";
import {
  BUILDING_USE_OPTIONS,
  DIRECTION_BASIS_OPTIONS,
  DIRECTION_OPTIONS,
  ELEVATOR_TYPE_OPTIONS,
  ENTRANCE_TYPE_OPTIONS,
  HEATING_FUEL_OPTIONS,
  HEATING_TYPE_OPTIONS,
  HVAC_OPTIONS,
  LAND_CATEGORY_OPTIONS,
  LAND_SHAPE_OPTIONS,
  LAND_USE_STATUS_OPTIONS,
  LOCATION_TRAIT_OPTIONS,
  LOAN_STATUS_OPTIONS,
  MAINTENANCE_BILLING_OPTIONS,
  MAINTENANCE_INCLUDE_OPTIONS,
  MOVE_IN_TYPE_OPTIONS,
  OPTION_ITEM_OPTIONS,
  OWNER_RELATION_OPTIONS,
  ROAD_ACCESS_OPTIONS,
  ROAD_PAVED_OPTIONS,
  STRUCTURE_TYPE_OPTIONS,
  TERRAIN_OPTIONS,
  TOILET_LOCATION_OPTIONS,
  ZONING_OPTIONS,
} from "./deal-options";

function allGroups(overrides: Partial<FieldSpec> & Pick<FieldSpec, "field_name" | "label" | "data_type" | "step" | "storage">): FieldSpec {
  return {
    is_required: false,
    validation_rule: "",
    naver_sync_note: "",
    category_groups: [...ALL_CATEGORY_GROUPS],
    ...overrides,
  };
}

function forGroups(
  groups: CategoryGroup[],
  overrides: Partial<FieldSpec> & Pick<FieldSpec, "field_name" | "label" | "data_type" | "step" | "storage">,
): FieldSpec {
  return {
    is_required: false,
    validation_rule: "",
    naver_sync_note: "",
    category_groups: groups,
    ...overrides,
  };
}

/** Step 1 — 기본정보 및 거래조건 (공통 컬럼) */
export const COMMON_STEP1_FIELDS: FieldSpec[] = [
  allGroups({
    field_name: "title",
    label: "매물 제목",
    data_type: "String",
    is_required: true,
    step: 1,
    storage: "column",
    validation_rule: "1자 이상",
    naver_sync_note: "한 줄 요약·특징이 드러나도록 작성",
  }),
  allGroups({
    field_name: "featureSummary",
    label: "매물 특징(한 줄)",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "선택, 200자 이내",
    naver_sync_note: "네이버 매물 특징 요약란에 대응",
  }),
  allGroups({
    field_name: "sido",
    label: "시/도",
    data_type: "String",
    is_required: true,
    step: 1,
    storage: "column",
    validation_rule: "필수",
    naver_sync_note: "소재지 시/도",
  }),
  allGroups({
    field_name: "sigungu",
    label: "시/군/구",
    data_type: "String",
    is_required: true,
    step: 1,
    storage: "column",
    validation_rule: "필수",
    naver_sync_note: "소재지 시/군/구",
  }),
  allGroups({
    field_name: "eupmyeondong",
    label: "읍/면/동",
    data_type: "String",
    is_required: true,
    step: 1,
    storage: "column",
    validation_rule: "필수",
    naver_sync_note: "소재지 읍/면/동",
  }),
  allGroups({
    field_name: "ri",
    label: "리",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "해당 시 입력",
  }),
  allGroups({
    field_name: "jibunMain",
    label: "본번",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "번지 본번",
  }),
  allGroups({
    field_name: "jibunSub",
    label: "부번",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "번지 부번",
  }),
  allGroups({
    field_name: "buildingName",
    label: "건물명/단지명",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "선택",
    naver_sync_note: "아파트·오피스텔은 단지명 권장",
  }),
  allGroups({
    field_name: "unitDong",
    label: "동",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "선택",
  }),
  allGroups({
    field_name: "unitHo",
    label: "호수",
    data_type: "String",
    step: 1,
    storage: "column",
    validation_rule: "선택",
    naver_sync_note: "상가·주택 일부 사용 시 '1층 일부' 등 상세 기입",
  }),
  allGroups({
    field_name: "loanStatus",
    label: "융자금",
    data_type: "Select",
    options: [...LOAN_STATUS_OPTIONS],
    step: 1,
    storage: "column",
    validation_rule: "목록에서 선택",
    naver_sync_note: "없음 / 시세 30% 이하 / 시세 30% 초과",
  }),
  allGroups({
    field_name: "moveInType",
    label: "입주 가능일 유형",
    data_type: "Select",
    options: [...MOVE_IN_TYPE_OPTIONS],
    is_required: true,
    step: 1,
    storage: "column",
    validation_rule: "즉시입주|협의가능|지정일",
  }),
  allGroups({
    field_name: "moveInDate",
    label: "입주 지정일",
    data_type: "Date",
    step: 1,
    storage: "column",
    validation_rule: "moveInType=지정일 시 YYYY-MM-DD 필수",
    naver_sync_note: "지정일 선택 시에만 입력",
  }),
  allGroups({
    field_name: "price",
    label: "매매가/분양가 (만원)",
    data_type: "Number",
    step: 1,
    storage: "column",
    validation_rule: "매매·분양권 시 0 초과",
  }),
  allGroups({
    field_name: "deposit",
    label: "보증금/전세가 (만원)",
    data_type: "Number",
    step: 1,
    storage: "column",
    validation_rule: "전세·월세·단기임대 시 0 이상",
  }),
  allGroups({
    field_name: "monthlyRent",
    label: "월세액 (만원)",
    data_type: "Number",
    step: 1,
    storage: "column",
    validation_rule: "월세·단기임대 시 0 초과",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "keyMoney",
    label: "권리금 (만원)",
    data_type: "Number",
    step: 1,
    storage: "column",
    validation_rule: "0 이상 숫자",
    naver_sync_note: "상가 권리금; 비공개 시 keyMoneyHidden 사용",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "keyMoneyHidden",
    label: "권리금 비공개",
    data_type: "Boolean",
    step: 1,
    storage: "column",
    validation_rule: "true/false",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "vatIncluded",
    label: "월세 VAT 포함",
    data_type: "Boolean",
    step: 1,
    storage: "column",
    validation_rule: "true=포함 / false=별도",
    naver_sync_note: "상가·사무실 월세 VAT 포함 여부 필수 확인",
  }),
];

/** Step 4 — 소유자 검증 + 설명·미디어 */
export const COMMON_STEP4_FIELDS: FieldSpec[] = [
  allGroups({
    field_name: "ownerName",
    label: "등기부상 소유자명",
    data_type: "String",
    is_required: true,
    step: 4,
    storage: "column",
    validation_rule: "필수",
    naver_sync_note: "네이버 소유자 검증용 필수",
  }),
  allGroups({
    field_name: "ownerRelation",
    label: "의뢰인 관계",
    data_type: "Select",
    options: [...OWNER_RELATION_OPTIONS],
    is_required: true,
    step: 4,
    storage: "column",
    validation_rule: "본인|대리인",
    naver_sync_note: "네이버 검증용 필수",
  }),
  allGroups({
    field_name: "ownerPhone",
    label: "연락처",
    data_type: "String",
    is_required: true,
    step: 4,
    storage: "column",
    validation_rule: "숫자·하이픈 포함 연락처",
    naver_sync_note: "네이버 검증용 필수",
  }),
  allGroups({
    field_name: "clientName",
    label: "의뢰인명(대리인 시)",
    data_type: "String",
    step: 4,
    storage: "column",
    validation_rule: "대리인일 때 권장",
  }),
  allGroups({
    field_name: "description",
    label: "상세 설명",
    data_type: "String",
    is_required: true,
    step: 4,
    storage: "column",
    validation_rule: "1자 이상",
  }),
];

/** A. 아파트/오피스텔 — Step 2·3 */
export const APT_OFFICE_FIELDS: FieldSpec[] = [
  forGroups(["APT_OFFICE"], {
    field_name: "naverComplexId",
    label: "네이버 단지 ID",
    data_type: "String",
    step: 2,
    storage: "column",
    validation_rule: "선택(수동 입력)",
    naver_sync_note: "단지 DB 연동 예약 필드",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "naverDongId",
    label: "네이버 동 ID",
    data_type: "String",
    step: 2,
    storage: "column",
    validation_rule: "선택",
    naver_sync_note: "단지 동 ID 연동 예약",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "supplyArea",
    label: "공급면적 (㎡)",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "exclusiveArea",
    label: "전용면적 (㎡)",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "floor",
    label: "해당층",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "정수",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "totalFloors",
    label: "총층수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 정수",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "rooms",
    label: "방 개수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "bathrooms",
    label: "욕실 개수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "direction",
    label: "방향",
    data_type: "Select",
    options: [...DIRECTION_OPTIONS],
    step: 2,
    storage: "column",
    validation_rule: "목록 선택",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "directionBasis",
    label: "방향 기준",
    data_type: "Select",
    options: [...DIRECTION_BASIS_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "거실|안방",
    naver_sync_note: "거실/안방 기준 방향",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "structureType",
    label: "내부 구조",
    data_type: "Select",
    options: [...STRUCTURE_TYPE_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "maintenanceFee",
    label: "월 평균 관리비 (만원)",
    data_type: "Number",
    step: 3,
    storage: "column",
    validation_rule: "0 이상",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "maintenanceIncludes",
    label: "관리비 포함 항목",
    data_type: "MultiSelect",
    options: [...MAINTENANCE_INCLUDE_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "다중 선택",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "maintenanceBilling",
    label: "관리비 부과 방식",
    data_type: "Select",
    options: [...MAINTENANCE_BILLING_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "정액|실비|미정",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "totalParking",
    label: "총 주차대수",
    data_type: "Number",
    step: 3,
    storage: "specs",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "parkingPerHousehold",
    label: "세대당 주차대수",
    data_type: "Number",
    step: 3,
    storage: "specs",
    validation_rule: "0 이상 숫자",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "entranceType",
    label: "현관구조",
    data_type: "Select",
    options: [...ENTRANCE_TYPE_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "heatingType",
    label: "난방방식",
    data_type: "Select",
    options: [...HEATING_TYPE_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "heatingFuel",
    label: "난방연료",
    data_type: "Select",
    options: [...HEATING_FUEL_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["APT_OFFICE"], {
    field_name: "moveInExpectedDate",
    label: "입주예정일(분양권)",
    data_type: "Date",
    step: 2,
    storage: "specs",
    validation_rule: "YYYY-MM-DD",
    naver_sync_note: "분양권일 때 권장",
  }),
];

/** B. 빌라/원룸/주택 */
export const VILLA_HOUSE_FIELDS: FieldSpec[] = [
  forGroups(["VILLA_HOUSE"], {
    field_name: "landShareArea",
    label: "대지 지분 면적 (㎡)",
    data_type: "Number",
    step: 2,
    storage: "specs",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "exclusiveArea",
    label: "전용면적 (㎡)",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "totalFloorArea",
    label: "연면적 (㎡)",
    data_type: "Number",
    step: 2,
    storage: "specs",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "buildingUse",
    label: "건축물대장 용도",
    data_type: "Select",
    options: [...BUILDING_USE_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
    naver_sync_note: "건축물대장상 용도",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "approvalDate",
    label: "승인일자(준공년월)",
    data_type: "String",
    step: 2,
    storage: "specs",
    validation_rule: "YYYY-MM 권장",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "floor",
    label: "해당층",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "정수",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "totalFloors",
    label: "총층수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 정수",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "isBasement",
    label: "지하층 여부",
    data_type: "Boolean",
    step: 2,
    storage: "specs",
    validation_rule: "true/false",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "isSemiBasement",
    label: "반지하 여부",
    data_type: "Boolean",
    step: 2,
    storage: "specs",
    validation_rule: "true/false",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "rooms",
    label: "방 수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "bathrooms",
    label: "욕실 수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "hasVeranda",
    label: "베란다/발코니",
    data_type: "Boolean",
    step: 2,
    storage: "specs",
    validation_rule: "true/false",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "hasElevator",
    label: "엘리베이터",
    data_type: "Boolean",
    step: 3,
    storage: "specs",
    validation_rule: "true/false",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "optionItems",
    label: "옵션 품목",
    data_type: "MultiSelect",
    options: [...OPTION_ITEM_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "다중 선택",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "parkingAvailable",
    label: "주차 가능",
    data_type: "Boolean",
    step: 3,
    storage: "specs",
    validation_rule: "true/false",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "totalParking",
    label: "총 주차대수",
    data_type: "Number",
    step: 3,
    storage: "specs",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["VILLA_HOUSE"], {
    field_name: "assignedParking",
    label: "세대별 지정주차",
    data_type: "Boolean",
    step: 3,
    storage: "specs",
    validation_rule: "true/false",
  }),
];

/** C. 상가/사무실/공장 */
export const RETAIL_OFFICE_FIELDS: FieldSpec[] = [
  forGroups(["RETAIL_OFFICE"], {
    field_name: "contractArea",
    label: "계약면적 (㎡)",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "specs",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "exclusiveArea",
    label: "전용면적 (㎡)",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 숫자",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "floor",
    label: "해당층",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "정수",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "totalFloors",
    label: "총층수",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 정수",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "locationTrait",
    label: "위치 특성",
    data_type: "Select",
    options: [...LOCATION_TRAIT_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
    naver_sync_note: "1층 전면, 코너 등",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "maintenanceFee",
    label: "관리비 (만원)",
    data_type: "Number",
    step: 3,
    storage: "column",
    validation_rule: "0 이상",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "maintenanceNote",
    label: "관리비 포함 내역",
    data_type: "String",
    step: 3,
    storage: "specs",
    validation_rule: "텍스트",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "businessType",
    label: "현재 업종",
    data_type: "String",
    step: 2,
    storage: "column",
    validation_rule: "선택",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "recommendedBusiness",
    label: "추천 업종",
    data_type: "String",
    step: 2,
    storage: "specs",
    validation_rule: "선택",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "illegalBuilding",
    label: "위반건축물 여부",
    data_type: "Boolean",
    is_required: true,
    step: 2,
    storage: "specs",
    validation_rule: "true/false 필수",
    naver_sync_note: "상가 허가 업종 진입 시 필수 체크",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "powerCapacityKw",
    label: "전력 용량 (kW)",
    data_type: "Number",
    step: 3,
    storage: "specs",
    validation_rule: "0 이상 숫자",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "hvacType",
    label: "난방/냉방 시설",
    data_type: "Select",
    options: [...HVAC_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "toiletLocation",
    label: "화장실 위치",
    data_type: "Select",
    options: [...TOILET_LOCATION_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "totalParking",
    label: "주차대수",
    data_type: "Number",
    step: 3,
    storage: "specs",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "freeParking",
    label: "무료주차 대수",
    data_type: "Number",
    step: 3,
    storage: "specs",
    validation_rule: "0 이상 정수",
  }),
  forGroups(["RETAIL_OFFICE"], {
    field_name: "elevatorType",
    label: "엘리베이터",
    data_type: "Select",
    options: [...ELEVATOR_TYPE_OPTIONS],
    step: 3,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
];

/** D. 토지/임야 */
export const LAND_FIELDS: FieldSpec[] = [
  forGroups(["LAND"], {
    field_name: "exclusiveArea",
    label: "대지면적 (㎡)",
    data_type: "Number",
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "0 초과 숫자",
    naver_sync_note: "평 단위 자동환산(×0.3025) 표시",
  }),
  forGroups(["LAND"], {
    field_name: "landCategory",
    label: "지목",
    data_type: "Select",
    options: [...LAND_CATEGORY_OPTIONS],
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "목록 선택",
    naver_sync_note: "대·전·답·임야 등",
  }),
  forGroups(["LAND"], {
    field_name: "zoning",
    label: "용도지역",
    data_type: "Select",
    options: [...ZONING_OPTIONS],
    is_required: true,
    step: 2,
    storage: "column",
    validation_rule: "목록 선택",
  }),
  forGroups(["LAND"], {
    field_name: "roadAccess",
    label: "도로접면",
    data_type: "Select",
    options: [...ROAD_ACCESS_OPTIONS],
    is_required: true,
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["LAND"], {
    field_name: "roadPaved",
    label: "도로 포장",
    data_type: "Select",
    options: [...ROAD_PAVED_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "포장|비포장",
  }),
  forGroups(["LAND"], {
    field_name: "terrain",
    label: "지형",
    data_type: "Select",
    options: [...TERRAIN_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["LAND"], {
    field_name: "landShape",
    label: "지세/형상",
    data_type: "Select",
    options: [...LAND_SHAPE_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
  forGroups(["LAND"], {
    field_name: "landUseStatus",
    label: "현재 이용 상황",
    data_type: "Select",
    options: [...LAND_USE_STATUS_OPTIONS],
    step: 2,
    storage: "specs",
    validation_rule: "목록 선택",
  }),
];

export const ALL_FIELD_SPECS: FieldSpec[] = [
  ...COMMON_STEP1_FIELDS,
  ...APT_OFFICE_FIELDS,
  ...VILLA_HOUSE_FIELDS,
  ...RETAIL_OFFICE_FIELDS,
  ...LAND_FIELDS,
  ...COMMON_STEP4_FIELDS,
];

export function getFieldsForGroup(group: CategoryGroup, step?: FormStep): FieldSpec[] {
  return ALL_FIELD_SPECS.filter(
    (f) => f.category_groups.includes(group) && (step == null || f.step === step),
  );
}

export function getFieldsForStep(group: CategoryGroup, step: FormStep): FieldSpec[] {
  return getFieldsForGroup(group, step);
}

/** Deduplicate by field_name keeping first (column fields shared across groups). */
export function uniqueFields(fields: FieldSpec[]): FieldSpec[] {
  const seen = new Set<string>();
  return fields.filter((f) => {
    if (seen.has(f.field_name)) return false;
    seen.add(f.field_name);
    return true;
  });
}
