/** Supabase row → 앱(Prisma 형태) 매핑 */

export function mapPropertyRow(row: Record<string, unknown>) {
  return {
    id: String(row.id),
    manageCode: String(row.manage_code ?? ""),
    title: String(row.title ?? ""),
    description: String(row.description ?? ""),
    type: String(row.type ?? "SALE") as never,
    category: String(row.category ?? "APARTMENT") as never,
    price: Number(row.price ?? 0),
    deposit: row.deposit == null ? null : Number(row.deposit),
    monthlyRent: row.monthly_rent == null ? null : Number(row.monthly_rent),
    isJeonse: Boolean(row.is_jeonse),
    dealSubType: (row.deal_sub_type as string | null) ?? null,
    area: (row.area as string | null) ?? null,
    address: String(row.address ?? ""),
    region: String(row.region ?? ""),
    sido: (row.sido as string | null) ?? null,
    sigungu: (row.sigungu as string | null) ?? null,
    eupmyeondong: (row.eupmyeondong as string | null) ?? null,
    ri: (row.ri as string | null) ?? null,
    jibunMain: (row.jibun_main as string | null) ?? null,
    jibunSub: (row.jibun_sub as string | null) ?? null,
    buildingName: (row.building_name as string | null) ?? null,
    exclusiveArea: row.exclusive_area == null ? null : Number(row.exclusive_area),
    supplyArea: row.supply_area == null ? null : Number(row.supply_area),
    floor: row.floor == null ? null : Number(row.floor),
    totalFloors: row.total_floors == null ? null : Number(row.total_floors),
    direction: (row.direction as string | null) ?? null,
    builtYear: row.built_year == null ? null : Number(row.built_year),
    parking: (row.parking as string | null) ?? null,
    rooms: row.rooms == null ? null : Number(row.rooms),
    bathrooms: row.bathrooms == null ? null : Number(row.bathrooms),
    unitDong: (row.unit_dong as string | null) ?? null,
    unitHo: (row.unit_ho as string | null) ?? null,
    maintenanceFee: row.maintenance_fee == null ? null : Number(row.maintenance_fee),
    keyMoney: row.key_money == null ? null : Number(row.key_money),
    keyMoneyHidden: Boolean(row.key_money_hidden),
    vatIncluded: row.vat_included == null ? null : Boolean(row.vat_included),
    businessType: (row.business_type as string | null) ?? null,
    landCategory: (row.land_category as string | null) ?? null,
    zoning: (row.zoning as string | null) ?? null,
    loanStatus: (row.loan_status as string | null) ?? null,
    moveInType: (row.move_in_type as string | null) ?? null,
    featureSummary: (row.feature_summary as string | null) ?? null,
    ownerName: (row.owner_name as string | null) ?? null,
    ownerRelation: (row.owner_relation as string | null) ?? null,
    ownerPhone: (row.owner_phone as string | null) ?? null,
    clientName: (row.client_name as string | null) ?? null,
    naverComplexId: (row.naver_complex_id as string | null) ?? null,
    naverDongId: (row.naver_dong_id as string | null) ?? null,
    specs: JSON.stringify(row.specs ?? {}),
    tags: JSON.stringify(row.tags ?? []),
    moveInDate: (row.move_in_date as string | null) ?? null,
    images: JSON.stringify(row.images ?? []),
    featured: Boolean(row.featured),
    status: String(row.status ?? "ACTIVE") as never,
    publishedAt: new Date(String(row.published_at ?? Date.now())),
    createdAt: new Date(String(row.created_at ?? Date.now())),
    updatedAt: new Date(String(row.updated_at ?? Date.now())),
  };
}

export function mapAuctionRow(row: Record<string, unknown>) {
  return {
    id: String(row.id),
    manageCode: String(row.manage_code ?? ""),
    caseNumber: String(row.case_number ?? ""),
    itemNo: Number(row.item_no ?? 1),
    title: String(row.title ?? ""),
    description: String(row.description ?? ""),
    appraisalPrice: Number(row.appraisal_price ?? 0),
    recommendedPrice: Number(row.recommended_price ?? 0),
    safetyGrade: String(row.safety_grade ?? "SAFE") as never,
    status: String(row.status ?? "ONGOING") as never,
    dDay: Number(row.d_day ?? 0),
    images: JSON.stringify(row.images ?? []),
    reportUrl: (row.report_url as string | null) ?? null,
    court: (row.court as string | null) ?? null,
    saleDate: row.sale_date ? new Date(String(row.sale_date)) : null,
    address: (row.address as string | null) ?? null,
    address2: (row.address2 as string | null) ?? null,
    region: (row.region as string | null) ?? null,
    auctionType: (row.auction_type as string | null) ?? null,
    itemType: (row.item_type as string | null) ?? null,
    auctionTarget: (row.auction_target as string | null) ?? null,
    bidMethod: (row.bid_method as string | null) ?? null,
    landArea: row.land_area == null ? null : Number(row.land_area),
    buildingArea: row.building_area == null ? null : Number(row.building_area),
    minPrice: row.min_price == null ? null : Number(row.min_price),
    bidDeposit: row.bid_deposit == null ? null : Number(row.bid_deposit),
    claimAmount: row.claim_amount == null ? null : Number(row.claim_amount),
    debtorOwner: (row.debtor_owner as string | null) ?? null,
    creditor: (row.creditor as string | null) ?? null,
    attachments: JSON.stringify(row.attachments ?? []),
    rightsAnalysis: (row.rights_analysis as string | null) ?? null,
    memo: (row.memo as string | null) ?? null,
    winningPrice: row.winning_price == null ? null : Number(row.winning_price),
    winningRatio: row.winning_ratio == null ? null : Number(row.winning_ratio),
    bidderCount: row.bidder_count == null ? null : Number(row.bidder_count),
    secondBidAmount: row.second_bid_amount == null ? null : Number(row.second_bid_amount),
    featured: Boolean(row.featured),
    publishedAt: new Date(String(row.published_at ?? Date.now())),
    createdAt: new Date(String(row.created_at ?? Date.now())),
    updatedAt: new Date(String(row.updated_at ?? Date.now())),
  };
}

export function mapLegalRow(row: Record<string, unknown>) {
  return {
    id: String(row.id),
    category: String(row.category ?? ""),
    question: String(row.question ?? ""),
    content: String(row.content ?? ""),
    authorName: String(row.author_name ?? ""),
    phone: (row.phone as string | null) ?? null,
    answer: (row.answer as string | null) ?? null,
    answerer: (row.answerer as string | null) ?? null,
    status: String(row.status ?? "PENDING") as never,
    isPublic: Boolean(row.is_public),
    isSecret: Boolean(row.is_secret),
    accessCode: String(row.access_code ?? ""),
    suggestConsult: Boolean(row.suggest_consult),
    answeredAt: row.answered_at ? new Date(String(row.answered_at)) : null,
    createdAt: new Date(String(row.created_at ?? Date.now())),
    updatedAt: new Date(String(row.updated_at ?? Date.now())),
  };
}

export function mapStoryRow(row: Record<string, unknown>) {
  return {
    id: String(row.id),
    category: String(row.category ?? ""),
    title: String(row.title ?? ""),
    content: String(row.content ?? ""),
    authorName: String(row.author_name ?? ""),
    status: String(row.status ?? "PUBLISHED") as never,
    createdAt: new Date(String(row.created_at ?? Date.now())),
    updatedAt: new Date(String(row.updated_at ?? Date.now())),
  };
}
