import type { Property, PropertyCategory, PropertyType } from "@prisma/client";

/**
 * Split-View 매물 목업용 샘플.
 * PropertyForm / Prisma Property 필드와 동일 형식으로 매핑.
 */
export type SampleProperty = Property;

function base(
  partial: Omit<Property, "createdAt" | "updatedAt" | "publishedAt" | "status" | "featured" | "manageCode"> & {
    manageCode?: string;
    publishedAt?: Date;
    featured?: boolean;
    status?: Property["status"];
  },
): SampleProperty {
  const now = new Date("2026-07-11T09:00:00+09:00");
  const seq = Number(String(partial.id).replace(/\D/g, "")) || 1;
  return {
    featured: false,
    status: "ACTIVE",
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    ...partial,
    manageCode: partial.manageCode ?? `매물_${String(seq).padStart(8, "0")}`,
  };
}

const IMG = {
  apt1: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80",
  apt2: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80",
  apt3: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80",
  villa: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80",
  retail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=900&q=80",
  land: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=900&q=80",
} as const;

export const PROPERTY_SPLIT_SAMPLES: SampleProperty[] = [
  base({
    id: "sample-apt-1",
    title: "모아미래도메가시티1차 84㎡ 남동향",
    featureSummary: "내포 중심 · 즉시입주 · 학군 우수",
    description:
      "내포신도시 핵심 입지 모아미래도메가시티1차입니다.\n남동향 고층으로 채광이 뛰어나며, 단지 내 편의시설이 잘 갖춰져 있습니다.\n\n현장 방문 및 실거래가 상담 환영합니다.",
    type: "SALE" as PropertyType,
    category: "APARTMENT" as PropertyCategory,
    price: 31000,
    deposit: null,
    monthlyRent: null,
    isJeonse: false,
    dealSubType: null,
    area: null,
    address: "충남 홍성군 홍북읍 신경리 123",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "123",
    jibunSub: null,
    buildingName: "모아미래도메가시티1차",
    exclusiveArea: 84.99,
    supplyArea: 112,
    floor: 8,
    totalFloors: 25,
    direction: "남동향",
    builtYear: 2021,
    parking: null,
    rooms: 3,
    bathrooms: 2,
    unitDong: "102동",
    unitHo: "803호",
    maintenanceFee: 18,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "시세 30% 이하",
    moveInType: "즉시입주",
    moveInDate: null,
    ownerName: "홍길동",
    ownerRelation: "본인",
    ownerPhone: "010-0000-0000",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      directionBasis: "거실 기준",
      structureType: "방3·욕실2",
      maintenanceIncludes: ["수도", "인터넷"],
      maintenanceBilling: "실비정산",
      totalParking: 980,
      parkingPerHousehold: 1.2,
      entranceType: "계단식",
      heatingType: "개별난방",
      heatingFuel: "도시가스",
    }),
    tags: JSON.stringify(["급매", "즉시입주", "역세권"]),
    images: JSON.stringify([IMG.apt1, IMG.apt2, IMG.apt3]),
    featured: true,
  }),
  base({
    id: "sample-apt-2",
    title: "내포자이 전세 84㎡",
    featureSummary: "전세 · 남향 · 학원가 인접",
    description: "내포자이 단지 전세 매물입니다.\n거실 확장형으로 실사용 공간이 넓습니다.",
    type: "RENT" as PropertyType,
    category: "APARTMENT" as PropertyCategory,
    price: 0,
    deposit: 28000,
    monthlyRent: null,
    isJeonse: true,
    dealSubType: "JEONSE",
    area: null,
    address: "충남 홍성군 홍북읍 신경리 45",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "45",
    jibunSub: "1",
    buildingName: "내포자이",
    exclusiveArea: 84.5,
    supplyArea: 110,
    floor: 15,
    totalFloors: 28,
    direction: "남향",
    builtYear: 2019,
    parking: null,
    rooms: 3,
    bathrooms: 2,
    unitDong: "101동",
    unitHo: "1502호",
    maintenanceFee: 16,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "협의가능",
    moveInDate: null,
    ownerName: "김소유",
    ownerRelation: "본인",
    ownerPhone: "010-1111-2222",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      heatingType: "개별난방",
      heatingFuel: "도시가스",
      totalParking: 1200,
      parkingPerHousehold: 1.1,
    }),
    tags: JSON.stringify(["학군"]),
    images: JSON.stringify([IMG.apt2, IMG.apt1]),
    publishedAt: new Date("2026-07-08T09:00:00+09:00"),
  }),
  base({
    id: "sample-villa-1",
    title: "홍북읍 신축 빌라 투룸",
    featureSummary: "신축 · 주차 가능 · 즉시입주",
    description: "신축급 빌라 투룸입니다. 엘리베이터와 주차장이 구비되어 있습니다.",
    type: "SALE" as PropertyType,
    category: "ROW_HOUSE" as PropertyCategory,
    price: 18500,
    deposit: null,
    monthlyRent: null,
    isJeonse: false,
    dealSubType: null,
    area: null,
    address: "충남 홍성군 홍북읍 신경리 78",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "78",
    jibunSub: null,
    buildingName: "미래빌",
    exclusiveArea: 59.2,
    supplyArea: null,
    floor: 3,
    totalFloors: 5,
    direction: "남서향",
    builtYear: 2024,
    parking: null,
    rooms: 2,
    bathrooms: 1,
    unitDong: null,
    unitHo: "302호",
    maintenanceFee: null,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "즉시입주",
    moveInDate: null,
    ownerName: "이건축",
    ownerRelation: "본인",
    ownerPhone: "010-3333-4444",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      landShareArea: 28.5,
      totalFloorArea: 210,
      buildingUse: "다세대주택",
      approvalDate: "2024-03",
      hasVeranda: true,
      hasElevator: true,
      optionItems: ["에어컨", "냉장고", "세탁기"],
      parkingAvailable: true,
      totalParking: 12,
      assignedParking: 1,
    }),
    tags: JSON.stringify(["즉시입주"]),
    images: JSON.stringify([IMG.villa]),
    publishedAt: new Date("2026-07-05T09:00:00+09:00"),
  }),
  base({
    id: "sample-retail-1",
    title: "내포 중심상가 1층 코너",
    featureSummary: "유동인구 우수 · 코너 입지",
    description: "내포신도시 중심 상권 1층 코너 상가입니다.\n현재 공실이며 다양한 업종 입점이 가능합니다.",
    type: "RENT" as PropertyType,
    category: "RETAIL" as PropertyCategory,
    price: 0,
    deposit: 5000,
    monthlyRent: 180,
    isJeonse: false,
    dealSubType: "MONTHLY",
    area: null,
    address: "충남 홍성군 홍북읍 신경리 200",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "200",
    jibunSub: null,
    buildingName: "내포센트럴타워",
    exclusiveArea: 66.1,
    supplyArea: null,
    floor: 1,
    totalFloors: 8,
    direction: null,
    builtYear: 2020,
    parking: null,
    rooms: null,
    bathrooms: null,
    unitDong: null,
    unitHo: "105호",
    maintenanceFee: 12,
    keyMoney: 3000,
    keyMoneyHidden: false,
    vatIncluded: false,
    businessType: "공실",
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "즉시입주",
    moveInDate: null,
    ownerName: "박상가",
    ownerRelation: "대리인",
    ownerPhone: "010-5555-6666",
    clientName: "박대리",
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      contractArea: 82,
      locationTrait: "코너 · 대로변",
      recommendedBusiness: "카페 · 의원 · 편의점",
      illegalBuilding: false,
      maintenanceNote: "전기·수도 실비",
      powerCapacityKw: 30,
      hvacType: "개별 냉난방",
      toiletLocation: "내부",
      totalParking: 40,
      freeParking: 2,
      elevatorType: "승객용",
    }),
    tags: JSON.stringify(["대로변"]),
    images: JSON.stringify([IMG.retail, IMG.apt3]),
    publishedAt: new Date("2026-07-01T09:00:00+09:00"),
  }),
  base({
    id: "sample-land-1",
    title: "홍북읍 주거용지 330㎡",
    featureSummary: "도로접 · 건축 가능지",
    description: "주거지역 토지입니다. 건축 상담 가능합니다.",
    type: "SALE" as PropertyType,
    category: "LAND" as PropertyCategory,
    price: 42000,
    deposit: null,
    monthlyRent: null,
    isJeonse: false,
    dealSubType: null,
    area: null,
    address: "충남 홍성군 홍북읍 신경리 산12",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "산12",
    jibunSub: null,
    buildingName: null,
    exclusiveArea: 330,
    supplyArea: null,
    floor: null,
    totalFloors: null,
    direction: null,
    builtYear: null,
    parking: null,
    rooms: null,
    bathrooms: null,
    unitDong: null,
    unitHo: null,
    maintenanceFee: null,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: "대",
    zoning: "제2종일반주거지역",
    loanStatus: "없음",
    moveInType: "협의가능",
    moveInDate: null,
    ownerName: "최토지",
    ownerRelation: "본인",
    ownerPhone: "010-7777-8888",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      roadAccess: "중로한면",
      roadPaved: "포장",
      terrain: "평지",
      landShape: "정방형",
      landUseStatus: "나대지",
    }),
    tags: JSON.stringify([]),
    images: JSON.stringify([IMG.land]),
    publishedAt: new Date("2026-06-28T09:00:00+09:00"),
  }),
  base({
    id: "sample-officetel-1",
    title: "내포 오피스텔 월세",
    featureSummary: "풀옵션 · 단기 가능",
    description: "풀옵션 오피스텔 월세입니다. 단기임대 협의 가능합니다.",
    type: "RENT" as PropertyType,
    category: "OFFICETEL" as PropertyCategory,
    price: 0,
    deposit: 1000,
    monthlyRent: 55,
    isJeonse: false,
    dealSubType: "MONTHLY",
    area: null,
    address: "충남 홍성군 홍북읍 신경리 88",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "88",
    jibunSub: null,
    buildingName: "내포스테이",
    exclusiveArea: 29.8,
    supplyArea: 42,
    floor: 12,
    totalFloors: 18,
    direction: "동향",
    builtYear: 2022,
    parking: null,
    rooms: 1,
    bathrooms: 1,
    unitDong: "A동",
    unitHo: "1205호",
    maintenanceFee: 8,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "지정일",
    moveInDate: "2026-08-01",
    ownerName: "정오피",
    ownerRelation: "본인",
    ownerPhone: "010-9999-0000",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      heatingType: "중앙난방",
      heatingFuel: "지역난방",
      totalParking: 200,
      parkingPerHousehold: 0.8,
    }),
    tags: JSON.stringify(["즉시입주"]),
    images: JSON.stringify([IMG.apt3, IMG.apt1]),
    publishedAt: new Date("2026-07-10T09:00:00+09:00"),
  }),
  base({
    id: "sample-apt-3",
    title: "한양수자인 매매 74㎡",
    featureSummary: "역세권 · 남향 · 올수리",
    description: "올수리 완료된 한양수자인 매매 매물입니다.",
    type: "SALE" as PropertyType,
    category: "APARTMENT" as PropertyCategory,
    price: 26500,
    deposit: null,
    monthlyRent: null,
    isJeonse: false,
    dealSubType: null,
    area: null,
    address: "충남 홍성군 홍북읍 신경리 56",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "56",
    jibunSub: null,
    buildingName: "한양수자인에듀포레",
    exclusiveArea: 74.2,
    supplyArea: 98,
    floor: 6,
    totalFloors: 22,
    direction: "남향",
    builtYear: 2018,
    parking: null,
    rooms: 3,
    bathrooms: 2,
    unitDong: "103동",
    unitHo: "602호",
    maintenanceFee: 14,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "협의가능",
    moveInDate: null,
    ownerName: "윤매매",
    ownerRelation: "본인",
    ownerPhone: "010-2222-3333",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      heatingType: "개별난방",
      heatingFuel: "도시가스",
      totalParking: 800,
      parkingPerHousehold: 1.0,
    }),
    tags: JSON.stringify(["역세권"]),
    images: JSON.stringify([IMG.apt2, IMG.apt3]),
    publishedAt: new Date("2026-07-09T09:00:00+09:00"),
  }),
  base({
    id: "sample-apt-4",
    title: "내포LH 월세 59㎡",
    featureSummary: "월세 · 즉시입주",
    description: "실입주 가능한 LH 단지 월세입니다.",
    type: "RENT" as PropertyType,
    category: "APARTMENT" as PropertyCategory,
    price: 0,
    deposit: 2000,
    monthlyRent: 70,
    isJeonse: false,
    dealSubType: "MONTHLY",
    area: null,
    address: "충남 홍성군 홍북읍 신경리 90",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "90",
    jibunSub: null,
    buildingName: "내포LH1단지",
    exclusiveArea: 59.9,
    supplyArea: 84,
    floor: 4,
    totalFloors: 15,
    direction: "남동향",
    builtYear: 2017,
    parking: null,
    rooms: 3,
    bathrooms: 1,
    unitDong: "201동",
    unitHo: "404호",
    maintenanceFee: 10,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "즉시입주",
    moveInDate: null,
    ownerName: "강월세",
    ownerRelation: "본인",
    ownerPhone: "010-4444-5555",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({ heatingType: "개별난방", heatingFuel: "도시가스" }),
    tags: JSON.stringify(["즉시입주"]),
    images: JSON.stringify([IMG.apt1]),
    publishedAt: new Date("2026-07-07T09:00:00+09:00"),
  }),
  base({
    id: "sample-office-1",
    title: "지식산업센터 사무실",
    featureSummary: "엘리베이터 · 주차 넉넉",
    description: "지식산업센터 내 사무실입니다.",
    type: "RENT" as PropertyType,
    category: "OFFICE" as PropertyCategory,
    price: 0,
    deposit: 3000,
    monthlyRent: 120,
    isJeonse: false,
    dealSubType: "MONTHLY",
    area: null,
    address: "충남 홍성군 홍북읍 신경리 301",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "301",
    jibunSub: null,
    buildingName: "내포비즈타워",
    exclusiveArea: 52,
    supplyArea: null,
    floor: 5,
    totalFloors: 10,
    direction: null,
    builtYear: 2021,
    parking: null,
    rooms: null,
    bathrooms: null,
    unitDong: null,
    unitHo: "503호",
    maintenanceFee: 15,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: true,
    businessType: "사무실",
    landCategory: null,
    zoning: null,
    loanStatus: "없음",
    moveInType: "즉시입주",
    moveInDate: null,
    ownerName: "임오피",
    ownerRelation: "본인",
    ownerPhone: "010-6666-7777",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      contractArea: 68,
      powerCapacityKw: 20,
      hvacType: "중앙냉난방",
      toiletLocation: "공용",
      totalParking: 120,
      freeParking: 1,
      elevatorType: "승객용",
    }),
    tags: JSON.stringify([]),
    images: JSON.stringify([IMG.retail]),
    publishedAt: new Date("2026-07-03T09:00:00+09:00"),
  }),
  base({
    id: "sample-villa-2",
    title: "단독주택 매매",
    featureSummary: "마당 · 주차 2대",
    description: "마당이 있는 단독주택입니다.",
    type: "SALE" as PropertyType,
    category: "DETACHED" as PropertyCategory,
    price: 32000,
    deposit: null,
    monthlyRent: null,
    isJeonse: false,
    dealSubType: null,
    area: null,
    address: "충남 홍성군 홍북읍 신경리 15",
    region: "내포신도시",
    sido: "충청남도",
    sigungu: "홍성군",
    eupmyeondong: "홍북읍",
    ri: "신경리",
    jibunMain: "15",
    jibunSub: null,
    buildingName: null,
    exclusiveArea: 120,
    supplyArea: null,
    floor: 1,
    totalFloors: 2,
    direction: "남향",
    builtYear: 2010,
    parking: null,
    rooms: 4,
    bathrooms: 2,
    unitDong: null,
    unitHo: null,
    maintenanceFee: null,
    keyMoney: null,
    keyMoneyHidden: false,
    vatIncluded: null,
    businessType: null,
    landCategory: null,
    zoning: null,
    loanStatus: "시세 30% 이하",
    moveInType: "협의가능",
    moveInDate: null,
    ownerName: "한단독",
    ownerRelation: "본인",
    ownerPhone: "010-8888-9999",
    clientName: null,
    naverComplexId: null,
    naverDongId: null,
    specs: JSON.stringify({
      landShareArea: 198,
      totalFloorArea: 140,
      buildingUse: "단독주택",
      hasVeranda: true,
      parkingAvailable: true,
      totalParking: 2,
    }),
    tags: JSON.stringify(["급매"]),
    images: JSON.stringify([IMG.villa, IMG.land]),
    publishedAt: new Date("2026-06-30T09:00:00+09:00"),
  }),
];
