import type { Prisma } from "@prisma/client";
import { suggestPropertyTitle } from "../src/lib/property-fields";

type PropertySeed = Prisma.PropertyCreateManyInput;

type PropertySeedInput = Omit<PropertySeed, "address" | "region"> & {
  address?: string;
  region?: string;
  sido?: string;
  sigungu?: string;
  eupmyeondong?: string;
};

const S = (obj: unknown) => JSON.stringify(obj);

function base(partial: PropertySeedInput): PropertySeed {
  const sido = partial.sido ?? "충청남도";
  const sigungu = partial.sigungu ?? "홍성군";
  const eupmyeondong = partial.eupmyeondong ?? "홍북읍";
  return {
    ...partial,
    sido,
    sigungu,
    eupmyeondong,
    region: partial.region ?? (eupmyeondong.includes("홍성읍") ? "홍성" : "내포신도시"),
    address:
      partial.address ??
      [sido, sigungu, eupmyeondong, partial.buildingName].filter(Boolean).join(" "),
    loanStatus: partial.loanStatus ?? "없음",
    moveInType: partial.moveInType ?? (partial.moveInDate?.includes("-") ? "지정일" : "협의가능"),
    ownerName: partial.ownerName ?? "김○○",
    ownerRelation: partial.ownerRelation ?? "본인",
    ownerPhone: partial.ownerPhone ?? "010-1234-5678",
    tags: partial.tags ?? "[]",
    images: partial.images ?? "[]",
    specs: partial.specs ?? "{}",
    featured: partial.featured ?? false,
    status: partial.status ?? "ACTIVE",
  };
}

/** 아파트 10 — 내포·홍성 실거래 단지명·시세대 반영 */
const APARTMENTS: PropertySeed[] = [
  base({
    title: "반도유보라 마크에디션 84㎡ 남향",
    featureSummary: "내포 대장주 단지, 남향 중층",
    description: "홍북읍 신경리 반도유보라 마크에디션. 전용 84㎡ 남향, 학군·공원 인접. 실거래 3억대 중반 시세대.",
    type: "SALE",
    category: "APARTMENT",
    price: 35000,
    buildingName: "반도유보라 마크에디션",
    exclusiveArea: 84.9,
    supplyArea: 110,
    floor: 12,
    totalFloors: 29,
    direction: "남향",
    builtYear: 2023,
    rooms: 3,
    bathrooms: 2,
    unitDong: "101",
    unitHo: "1203",
    maintenanceFee: 19,
    moveInType: "즉시입주",
    eupmyeondong: "홍북읍",
    featured: true,
    tags: S(["즉시입주", "역세권"]),
    images: S(["/images/hero-naepo.jpg"]),
    specs: S({
      directionBasis: "거실",
      structureType: "계단식",
      maintenanceIncludes: ["수도", "인터넷"],
      maintenanceBilling: "정액",
      totalParking: 980,
      parkingPerHousehold: 1.2,
      entranceType: "계단식",
      heatingType: "개별난방",
      heatingFuel: "도시가스",
    }),
  }),
  base({
    title: "모아미래도메가시티1차 84㎡",
    featureSummary: "신축 대단지, 거래량 많은 실수요 단지",
    description: "내포신도시 모아미래도메가시티1차. 전용 84㎡, 전세가율 양호. 국가산단 배후 수요.",
    type: "SALE",
    category: "APARTMENT",
    price: 31000,
    buildingName: "모아미래도메가시티1차",
    exclusiveArea: 84.99,
    supplyArea: 112,
    floor: 8,
    totalFloors: 25,
    direction: "남동향",
    builtYear: 2024,
    rooms: 3,
    bathrooms: 2,
    unitDong: "105",
    unitHo: "804",
    maintenanceFee: 18,
    moveInType: "협의가능",
    tags: S(["신축"]),
    specs: S({ directionBasis: "안방", structureType: "계단식", heatingType: "개별난방", heatingFuel: "도시가스" }),
  }),
  base({
    title: "모아미래도메가시티2차 84㎡ 급매",
    featureSummary: "2차 단지 급매 협의",
    description: "모아미래도메가시티2차 전용 84㎡. 급매로 가격 협의 가능.",
    type: "SALE",
    category: "APARTMENT",
    price: 32900,
    buildingName: "모아미래도메가시티2차",
    exclusiveArea: 84.0,
    supplyArea: 109,
    floor: 15,
    totalFloors: 27,
    direction: "남향",
    builtYear: 2024,
    rooms: 3,
    bathrooms: 2,
    unitDong: "203",
    unitHo: "1501",
    maintenanceFee: 20,
    tags: S(["급매"]),
  }),
  base({
    title: "내포신도시 롯데캐슬 84㎡ 전세",
    featureSummary: "롯데캐슬 전세 1.5억대",
    description: "신대로 롯데캐슬 전용 84㎡ 전세. 즉시 입주 협의.",
    type: "RENT",
    category: "APARTMENT",
    price: 0,
    deposit: 15000,
    monthlyRent: 0,
    isJeonse: true,
    dealSubType: "JEONSE",
    buildingName: "내포신도시 롯데캐슬",
    exclusiveArea: 84.94,
    supplyArea: 111,
    floor: 10,
    totalFloors: 24,
    direction: "남향",
    builtYear: 2018,
    rooms: 3,
    bathrooms: 2,
    unitDong: "102",
    unitHo: "1002",
    maintenanceFee: 17,
    moveInType: "즉시입주",
    tags: S(["즉시입주"]),
  }),
  base({
    title: "경남아너스빌 59㎡ 월세",
    featureSummary: "소형 월세, 보증 1천만/월 70만",
    description: "청사로 경남아너스빌 전용 59㎡ 월세. 신혼·직장인 적합.",
    type: "RENT",
    category: "APARTMENT",
    price: 0,
    deposit: 1000,
    monthlyRent: 70,
    isJeonse: false,
    dealSubType: "MONTHLY",
    buildingName: "내포신도시 경남아너스빌",
    exclusiveArea: 59.88,
    supplyArea: 78,
    floor: 6,
    totalFloors: 20,
    direction: "동향",
    builtYear: 2016,
    rooms: 2,
    bathrooms: 1,
    unitDong: "101",
    unitHo: "602",
    maintenanceFee: 12,
  }),
  base({
    title: "중흥S-클래스더시티 84㎡",
    featureSummary: "예산 삽교 내포권 중흥S클래스",
    description: "예산군 삽교읍 중흥S-클래스더시티. 전용 84㎡ 실거래 3억 전후.",
    type: "SALE",
    category: "APARTMENT",
    price: 30000,
    buildingName: "중흥S-클래스더시티",
    exclusiveArea: 84.96,
    supplyArea: 108,
    floor: 12,
    totalFloors: 22,
    direction: "남향",
    builtYear: 2020,
    rooms: 3,
    bathrooms: 2,
    unitDong: "108",
    unitHo: "1205",
    sigungu: "예산군",
    eupmyeondong: "삽교읍",
    region: "내포신도시",
    maintenanceFee: 16,
  }),
  base({
    title: "효성해링턴플레이스 68㎡",
    featureSummary: "소형 실수요, 거래 꾸준",
    description: "홍북읍 효성해링턴플레이스 전용 68㎡. 1억 후반대 시세.",
    type: "SALE",
    category: "APARTMENT",
    price: 17900,
    buildingName: "효성해링턴플레이스",
    exclusiveArea: 68.0,
    supplyArea: 89,
    floor: 5,
    totalFloors: 18,
    direction: "남서향",
    builtYear: 2017,
    rooms: 3,
    bathrooms: 1,
    unitDong: "103",
    unitHo: "503",
    maintenanceFee: 13,
  }),
  base({
    title: "한울마을 모아엘가 84㎡",
    featureSummary: "홍학로 모아엘가",
    description: "홍북읍 한울마을 모아엘가 전용 84㎡. 실거래 2억대 초반.",
    type: "SALE",
    category: "APARTMENT",
    price: 22000,
    buildingName: "한울마을 모아엘가",
    exclusiveArea: 84.98,
    supplyArea: 107,
    floor: 9,
    totalFloors: 20,
    direction: "남향",
    builtYear: 2015,
    rooms: 3,
    bathrooms: 2,
    unitDong: "201",
    unitHo: "902",
    maintenanceFee: 15,
  }),
  base({
    title: "홍성자이 84㎡",
    featureSummary: "홍성읍 자이 브랜드",
    description: "홍성읍 홍성자이 전용 84㎡. 구도심 프리미엄 단지.",
    type: "SALE",
    category: "APARTMENT",
    price: 36500,
    buildingName: "홍성자이",
    exclusiveArea: 84.62,
    supplyArea: 110,
    floor: 14,
    totalFloors: 25,
    direction: "남향",
    builtYear: 2021,
    rooms: 3,
    bathrooms: 2,
    unitDong: "101",
    unitHo: "1401",
    eupmyeondong: "홍성읍",
    region: "홍성",
    maintenanceFee: 21,
    featured: true,
    tags: S(["역세권"]),
    images: S(["/images/hero-naepo.jpg"]),
  }),
  base({
    title: "e편한세상 내포 102㎡",
    featureSummary: "대형 평형 남향 고층",
    description: "e편한세상 내포 전용 102㎡. 학원가·공원 인접.",
    type: "SALE",
    category: "APARTMENT",
    price: 42000,
    buildingName: "e편한세상 내포",
    exclusiveArea: 102,
    supplyArea: 132,
    floor: 18,
    totalFloors: 28,
    direction: "남향",
    builtYear: 2020,
    rooms: 4,
    bathrooms: 2,
    unitDong: "104",
    unitHo: "1802",
    maintenanceFee: 24,
    moveInType: "즉시입주",
    tags: S(["즉시입주"]),
  }),
];

const OFFICETELS: PropertySeed[] = [
  base({
    title: "내포역세권 오피스텔 28㎡ 월세",
    featureSummary: "풀옵션, 역 도보권",
    description: "내포 중심 오피스텔 전용 28㎡. 보증 1천만/월 55만.",
    type: "RENT",
    category: "OFFICETEL",
    price: 0,
    deposit: 1000,
    monthlyRent: 55,
    dealSubType: "MONTHLY",
    buildingName: "내포역 오피스텔",
    exclusiveArea: 28,
    supplyArea: 38,
    floor: 9,
    totalFloors: 15,
    direction: "남향",
    builtYear: 2018,
    rooms: 1,
    bathrooms: 1,
    maintenanceFee: 8,
    moveInType: "즉시입주",
    tags: S(["역세권", "즉시입주"]),
    specs: S({ structureType: "복도식", heatingType: "개별난방", heatingFuel: "도시가스", optionItems: ["에어컨", "세탁기", "냉장고"] }),
  }),
  base({
    title: "내포 센트럴 오피스텔 33㎡ 매매",
    featureSummary: "투자·실거주 겸용",
    description: "중앙로 오피스텔 전용 33㎡ 매매.",
    type: "SALE",
    category: "OFFICETEL",
    price: 9800,
    buildingName: "내포 센트럴 오피스텔",
    exclusiveArea: 33,
    supplyArea: 42,
    floor: 12,
    totalFloors: 20,
    direction: "동향",
    builtYear: 2019,
    rooms: 1,
    bathrooms: 1,
    maintenanceFee: 10,
  }),
  base({
    title: "내포 센트럴 오피스텔 42㎡ 분양권",
    featureSummary: "2026 입주 예정 분양권",
    description: "분양권 전용 42㎡. 입주예정일 2026-06.",
    type: "PRE_SALE",
    category: "OFFICETEL",
    price: 31500,
    buildingName: "내포 센트럴 오피스텔",
    exclusiveArea: 42,
    supplyArea: 55,
    floor: 16,
    totalFloors: 22,
    direction: "남동향",
    moveInType: "지정일",
    moveInDate: "2026-06-30",
    tags: S(["분양권"]),
    specs: S({ moveInExpectedDate: "2026-06-30" }),
  }),
  base({
    title: "홍성읍 오피스텔 24㎡ 월세",
    featureSummary: "구도심 소형 월세",
    description: "홍성읍 중심가 오피스텔. 보증 500/월 40만.",
    type: "RENT",
    category: "OFFICETEL",
    price: 0,
    deposit: 500,
    monthlyRent: 40,
    dealSubType: "MONTHLY",
    buildingName: "홍성타워오피스텔",
    exclusiveArea: 24,
    floor: 5,
    totalFloors: 12,
    direction: "서향",
    builtYear: 2014,
    rooms: 1,
    bathrooms: 1,
    eupmyeondong: "홍성읍",
    region: "홍성",
    maintenanceFee: 6,
  }),
  base({
    title: "내포 비즈 오피스텔 45㎡ 전세",
    featureSummary: "업무·거주 겸용 전세",
    description: "전용 45㎡ 전세 1.2억.",
    type: "RENT",
    category: "OFFICETEL",
    price: 0,
    deposit: 12000,
    isJeonse: true,
    dealSubType: "JEONSE",
    buildingName: "내포비즈오피스텔",
    exclusiveArea: 45,
    supplyArea: 58,
    floor: 7,
    totalFloors: 18,
    direction: "남향",
    builtYear: 2020,
    rooms: 1,
    bathrooms: 1,
    maintenanceFee: 11,
  }),
  base({
    title: "내포 신축 오피스텔 36㎡ 매매",
    featureSummary: "신축급 풀옵션",
    description: "2022년 준공 오피스텔 매매.",
    type: "SALE",
    category: "OFFICETEL",
    price: 12500,
    buildingName: "내포 더샵 오피스텔",
    exclusiveArea: 36,
    supplyArea: 48,
    floor: 11,
    totalFloors: 19,
    direction: "남향",
    builtYear: 2022,
    rooms: 1,
    bathrooms: 1,
    maintenanceFee: 12,
    tags: S(["신축"]),
  }),
  base({
    title: "내포 오피스텔 단기임대 30㎡",
    featureSummary: "단기 3개월 이상",
    description: "단기임대 전용 30㎡. 보증 300/월 65만.",
    type: "SHORT_TERM",
    category: "OFFICETEL",
    price: 0,
    deposit: 300,
    monthlyRent: 65,
    dealSubType: "MONTHLY",
    buildingName: "내포스테이오피스텔",
    exclusiveArea: 30,
    floor: 4,
    totalFloors: 10,
    direction: "동향",
    builtYear: 2017,
    rooms: 1,
    bathrooms: 1,
    maintenanceFee: 7,
    moveInType: "즉시입주",
  }),
  base({
    title: "예산 삽교 오피스텔 32㎡",
    featureSummary: "삽교 내포권 오피스텔",
    description: "예산 삽교읍 오피스텔 매매.",
    type: "SALE",
    category: "OFFICETEL",
    price: 8500,
    buildingName: "삽교센트럴오피스텔",
    exclusiveArea: 32,
    floor: 8,
    totalFloors: 14,
    direction: "남향",
    builtYear: 2016,
    rooms: 1,
    bathrooms: 1,
    sigungu: "예산군",
    eupmyeondong: "삽교읍",
    region: "내포신도시",
    maintenanceFee: 9,
  }),
  base({
    title: "내포 오피스텔 59㎡ 복층형",
    featureSummary: "복층형 희소 매물",
    description: "전용 59㎡ 복층형 오피스텔 매매.",
    type: "SALE",
    category: "OFFICETEL",
    price: 18900,
    buildingName: "내포듀얼오피스텔",
    exclusiveArea: 59,
    supplyArea: 72,
    floor: 14,
    totalFloors: 16,
    direction: "남향",
    builtYear: 2021,
    rooms: 2,
    bathrooms: 1,
    maintenanceFee: 14,
    specs: S({ structureType: "복층형", heatingType: "개별난방", heatingFuel: "도시가스" }),
  }),
  base({
    title: "내포 오피스텔 분양권 38㎡",
    featureSummary: "프리미엄 협의",
    description: "입주 2027년 예정 분양권.",
    type: "PRE_SALE",
    category: "OFFICETEL",
    price: 26800,
    buildingName: "내포 미래오피스텔",
    exclusiveArea: 38,
    supplyArea: 50,
    floor: 10,
    totalFloors: 24,
    direction: "남서향",
    moveInType: "지정일",
    moveInDate: "2027-03-01",
    tags: S(["분양권"]),
    specs: S({ moveInExpectedDate: "2027-03-01" }),
  }),
];

const RETAILS: PropertySeed[] = Array.from({ length: 10 }, (_, i) => {
  const items = [
    { title: "홍성 중심가 1층 상가 임대", type: "RENT" as const, price: 0, deposit: 3000, monthlyRent: 150, keyMoney: 5000, area: 66, floor: 1, biz: "카페/음식점", region: "홍성", dong: "홍성읍", sale: false },
    { title: "내포 코너 상가 매매", type: "SALE" as const, price: 62000, deposit: null, monthlyRent: null, keyMoney: 8000, area: 88, floor: 1, biz: "카페", region: "내포신도시", dong: "홍북읍", sale: true },
    { title: "내포 교육로 2층 상가 임대", type: "RENT" as const, price: 0, deposit: 8000, monthlyRent: 420, keyMoney: 0, area: 210, floor: 2, biz: "학원/병원", region: "내포신도시", dong: "홍북읍", sale: false },
    { title: "내포 상업지구 1층 전면 상가", type: "SALE" as const, price: 78000, deposit: null, monthlyRent: null, keyMoney: 12000, area: 95, floor: 1, biz: "편의점", region: "내포신도시", dong: "홍북읍", sale: true },
    { title: "홍성읍 먹자골목 상가 월세", type: "RENT" as const, price: 0, deposit: 2000, monthlyRent: 120, keyMoney: 3000, area: 45, floor: 1, biz: "음식점", region: "홍성", dong: "홍성읍", sale: false },
    { title: "내포 지하상가 임대", type: "RENT" as const, price: 0, deposit: 1500, monthlyRent: 80, keyMoney: 1000, area: 40, floor: -1, biz: "소매", region: "내포신도시", dong: "홍북읍", sale: false },
    { title: "삽교 대로변 상가 매매", type: "SALE" as const, price: 45000, deposit: null, monthlyRent: null, keyMoney: 4000, area: 72, floor: 1, biz: "미용실", region: "내포신도시", dong: "삽교읍", sale: true },
    { title: "내포 3층 근린상가 임대", type: "RENT" as const, price: 0, deposit: 4000, monthlyRent: 200, keyMoney: 0, area: 120, floor: 3, biz: "사무실겸용", region: "내포신도시", dong: "홍북읍", sale: false },
    { title: "홍성 터미널 인근 상가", type: "SALE" as const, price: 52000, deposit: null, monthlyRent: null, keyMoney: 6000, area: 80, floor: 1, biz: "분식/카페", region: "홍성", dong: "홍성읍", sale: true },
    { title: "내포 주상복합 1층 상가 월세", type: "RENT" as const, price: 0, deposit: 5000, monthlyRent: 250, keyMoney: 7000, area: 55, floor: 1, biz: "약국", region: "내포신도시", dong: "홍북읍", sale: false },
  ][i];
  return base({
    title: items.title,
    featureSummary: items.biz,
    description: `${items.title}. 네이버부동산 상가 등록 규격 샘플. 현재/추천 업종: ${items.biz}.`,
    type: items.type,
    category: "RETAIL",
    price: items.price,
    deposit: items.deposit,
    monthlyRent: items.monthlyRent,
    keyMoney: items.keyMoney,
    keyMoneyHidden: i === 5,
    vatIncluded: true,
    exclusiveArea: items.area,
    floor: items.floor,
    totalFloors: 5,
    businessType: items.biz,
    buildingName: `샘플상가${i + 1}`,
    unitHo: items.floor === 1 ? "1층 일부" : `${items.floor}층`,
    region: items.region,
    eupmyeondong: items.dong,
    sigungu: items.dong === "삽교읍" ? "예산군" : "홍성군",
    maintenanceFee: 20 + i * 2,
    featured: i === 1,
    tags: S(items.floor === 1 ? ["대로변"] : []),
    specs: S({
      contractArea: items.area * 1.15,
      locationTrait: items.floor === 1 ? "1층 전면" : "내부",
      illegalBuilding: false,
      recommendedBusiness: items.biz,
      powerCapacityKw: 10 + i,
      hvacType: "천장형",
      toiletLocation: "내부",
      totalParking: 5 + i,
      freeParking: 2,
      elevatorType: "승객용",
      maintenanceNote: "전기·수도 별도",
    }),
  });
});

const OFFICES: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: [
      "내포 업무시설 3층 매매",
      "내포 IT센터 5층 임대",
      "내포 비즈니스타워 7층",
      "홍성읍 소형 사무실 월세",
      "내포 공유오피스형 임대",
      "내포 업무로 2층 매매",
      "예산 삽교 사무실 임대",
      "내포 대형 오피스 4층",
      "내포 스타트업 사무실 단기",
      "홍성 관공서 인근 사무실",
    ][i],
    featureSummary: "업무시설 샘플",
    description: "내포·홍성 업무시설 네이버 규격 샘플 매물입니다.",
    type: (["SALE", "RENT", "SALE", "RENT", "RENT", "SALE", "RENT", "SALE", "SHORT_TERM", "RENT"] as const)[i],
    category: "OFFICE",
    price: [55000, 0, 72000, 0, 0, 48000, 0, 95000, 0, 0][i],
    deposit: [null, 5000, null, 1000, 2000, null, 2500, null, 500, 3000][i],
    monthlyRent: [null, 280, null, 60, 120, null, 90, null, 80, 150][i],
    dealSubType: [null, "MONTHLY", null, "MONTHLY", "MONTHLY", null, "MONTHLY", null, "MONTHLY", "MONTHLY"][i],
    buildingName: `내포오피스${i + 1}`,
    exclusiveArea: [120, 165, 98, 33, 55, 88, 70, 210, 40, 75][i],
    supplyArea: [145, 190, 120, 42, 68, 105, 85, 250, 50, 90][i],
    floor: [3, 5, 7, 2, 4, 2, 3, 4, 6, 2][i],
    totalFloors: 10,
    parking: `${1 + (i % 3)}대`,
    builtYear: 2018 + (i % 5),
    region: i === 3 || i === 9 ? "홍성" : "내포신도시",
    eupmyeondong: i === 3 || i === 9 ? "홍성읍" : i === 6 ? "삽교읍" : "홍북읍",
    sigungu: i === 6 ? "예산군" : "홍성군",
    vatIncluded: true,
    maintenanceFee: 15 + i,
    specs: S({
      contractArea: 130 + i * 10,
      locationTrait: i % 2 === 0 ? "엘리베이터 앞" : "내부",
      illegalBuilding: false,
      powerCapacityKw: 20 + i * 2,
      hvacType: "천장형",
      toiletLocation: "내부",
      elevatorType: "승객용",
      totalParking: 20 + i,
    }),
  }),
);

const ROW_HOUSES: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: [
      "홍성 연립 2층 전세",
      "홍성읍 연립 1층 매매",
      "내포 빌라 3층 매매",
      "내포 연립 월세",
      "홍성 신축 빌라 매매",
      "내포 복층 빌라",
      "홍북 연립 전세",
      "삽교 빌라 매매",
      "홍성 마당있는 연립",
      "내포 빌라 급매",
    ][i],
    description: "빌라/연립 네이버 규격 샘플. 건축물대장 용도·옵션 포함.",
    type: (["RENT", "SALE", "SALE", "RENT", "SALE", "SALE", "RENT", "SALE", "SALE", "SALE"] as const)[i],
    category: "ROW_HOUSE",
    price: [12000, 24500, 28000, 0, 32000, 35000, 14000, 22000, 26800, 25500][i],
    deposit: [12000, null, null, 2000, null, null, 14000, null, null, null][i],
    monthlyRent: [0, null, null, 55, null, null, 0, null, null, null][i],
    isJeonse: i === 0 || i === 6,
    dealSubType: i === 0 || i === 6 ? "JEONSE" : i === 3 ? "MONTHLY" : null,
    exclusiveArea: [78, 72, 84, 55, 90, 95, 70, 68, 82, 76][i],
    floor: [2, 1, 3, 2, 2, 3, 2, 1, 1, 2][i],
    totalFloors: [2, 2, 4, 3, 3, 4, 3, 2, 2, 3][i],
    rooms: [3, 3, 3, 2, 3, 4, 3, 3, 3, 3][i],
    bathrooms: [1, 1, 2, 1, 2, 2, 1, 1, 1, 1][i],
    direction: "남동향",
    builtYear: 2012 + i,
    region: [0, 1, 8].includes(i) || i === 4 ? "홍성" : "내포신도시",
    eupmyeondong: [0, 1, 4, 8].includes(i) ? "홍성읍" : i === 7 ? "삽교읍" : "홍북읍",
    sigungu: i === 7 ? "예산군" : "홍성군",
    moveInType: "협의가능",
    tags: S(i === 9 ? ["급매"] : []),
    specs: S({
      landShareArea: 40 + i,
      totalFloorArea: 90 + i * 5,
      buildingUse: "연립",
      approvalDate: `${2012 + i}-06`,
      hasVeranda: true,
      hasElevator: i > 4,
      optionItems: ["에어컨", "가스레인지"],
      parkingAvailable: true,
      totalParking: 4,
      assignedParking: i % 2 === 0,
      isBasement: false,
      isSemiBasement: false,
    }),
  }),
);

const MULTI_FAMILY: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: `내포·홍성 다세대 ${i + 1}호 샘플`,
    description: "다세대주택 네이버 규격 샘플 매물.",
    type: i % 3 === 0 ? "RENT" : "SALE",
    category: "MULTI_FAMILY",
    price: i % 3 === 0 ? (i % 2 === 0 ? 15000 : 0) : 28000 + i * 800,
    deposit: i % 3 === 0 ? (i % 2 === 0 ? 15000 : 2000) : null,
    monthlyRent: i % 3 === 0 && i % 2 !== 0 ? 50 : i % 3 === 0 ? 0 : null,
    isJeonse: i % 3 === 0 && i % 2 === 0,
    dealSubType: i % 3 === 0 ? (i % 2 === 0 ? "JEONSE" : "MONTHLY") : null,
    exclusiveArea: 60 + i * 3,
    floor: (i % 4) + 1,
    totalFloors: 4,
    rooms: 2 + (i % 2),
    bathrooms: 1,
    builtYear: 2015 + (i % 6),
    parking: "1대",
    direction: "남향",
    region: i > 7 ? "홍성" : "내포신도시",
    eupmyeondong: i > 7 ? "홍성읍" : "홍북읍",
    specs: S({
      buildingUse: "다세대",
      landShareArea: 25 + i,
      hasElevator: false,
      parkingAvailable: true,
      totalParking: 6,
      optionItems: ["에어컨", "세탁기"],
    }),
  }),
);

const DETACHED: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: [
      "홍성 단독주택 매매",
      "내포 전원주택형 단독",
      "홍북 다가구 수익형",
      "용봉 조망 단독",
      "홍성읍 리모델링 단독",
      "내포 신축 단독",
      "예산 단독주택",
      "홍성 마당넓은 단독",
      "내포 다가구 월세",
      "홍성 급매 단독",
    ][i],
    description: "단독·다가구 네이버 규격 샘플.",
    type: i === 8 ? "RENT" : "SALE",
    category: "DETACHED",
    price: i === 8 ? 0 : 18000 + i * 2500,
    deposit: i === 8 ? 3000 : null,
    monthlyRent: i === 8 ? 70 : null,
    dealSubType: i === 8 ? "MONTHLY" : null,
    exclusiveArea: 85 + i * 8,
    floor: 1,
    totalFloors: i === 2 || i === 8 ? 3 : 2,
    rooms: 3 + (i % 2),
    bathrooms: 1 + (i % 2),
    builtYear: 2005 + i,
    direction: "남향",
    region: [0, 4, 7, 9].includes(i) ? "홍성" : "내포신도시",
    eupmyeondong: [0, 4, 7, 9].includes(i) ? "홍성읍" : i === 6 ? "삽교읍" : "홍북읍",
    sigungu: i === 6 ? "예산군" : "홍성군",
    tags: S(i === 9 ? ["급매"] : []),
    specs: S({
      buildingUse: i === 2 || i === 8 ? "다가구" : "단독",
      landShareArea: 120 + i * 10,
      totalFloorArea: 140 + i * 12,
      hasVeranda: true,
      parkingAvailable: true,
      totalParking: 2,
      approvalDate: `${2005 + i}-09`,
    }),
  }),
);

const ONE_ROOMS: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: `내포·홍성 원룸·투룸 ${i + 1}`,
    featureSummary: i % 2 === 0 ? "원룸 풀옵션" : "투룸",
    description: "원룸·투룸 네이버 규격 샘플. 옵션·주차 정보 포함.",
    type: i < 7 ? "RENT" : i === 9 ? "SHORT_TERM" : "SALE",
    category: "ONE_ROOM",
    price: i < 7 || i === 9 ? 0 : 8500 + i * 200,
    deposit: i < 7 || i === 9 ? 500 + i * 100 : null,
    monthlyRent: i < 7 || i === 9 ? 35 + i * 3 : null,
    dealSubType: i < 7 || i === 9 ? "MONTHLY" : null,
    exclusiveArea: i % 2 === 0 ? 18 + i : 28 + i,
    floor: (i % 5) + 1,
    totalFloors: 5,
    rooms: i % 2 === 0 ? 1 : 2,
    bathrooms: 1,
    builtYear: 2016 + (i % 7),
    direction: "동향",
    region: i > 6 ? "홍성" : "내포신도시",
    eupmyeondong: i > 6 ? "홍성읍" : "홍북읍",
    maintenanceFee: 5 + (i % 4),
    moveInType: "즉시입주",
    tags: S(["즉시입주"]),
    specs: S({
      buildingUse: "다세대",
      hasElevator: i > 3,
      optionItems: ["에어컨", "세탁기", "냉장고", "인덕션", "옷장", "신발장"],
      parkingAvailable: i % 2 === 0,
      totalParking: 8,
      assignedParking: false,
      isSemiBasement: i === 0,
    }),
  }),
);

const FACTORIES: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: [
      "내포 지식산업센터 3층",
      "홍성 소형 공장 임대",
      "내포 창고겸 공장",
      "삽교 공장용지 건물",
      "내포 지식센터 5층 매매",
      "예산 공장 월세",
      "내포 물류형 공장",
      "홍성 근생공장",
      "내포 벤처공장",
      "내포 지식산업센터 분양권",
    ][i],
    description: "공장·지식산업센터 네이버 규격 샘플.",
    type: (["RENT", "RENT", "SALE", "SALE", "SALE", "RENT", "SALE", "RENT", "SALE", "PRE_SALE"] as const)[i],
    category: "FACTORY",
    price: [0, 0, 85000, 120000, 95000, 0, 110000, 0, 78000, 65000][i],
    deposit: [8000, 3000, null, null, null, 5000, null, 4000, null, null][i],
    monthlyRent: [350, 180, null, null, null, 220, null, 160, null, null][i],
    dealSubType: [0, 1, 5, 7].includes(i) ? "MONTHLY" : null,
    exclusiveArea: [180, 120, 350, 500, 220, 200, 400, 150, 160, 140][i],
    floor: [3, 1, 1, 1, 5, 1, 1, 2, 2, 8][i],
    totalFloors: [8, 2, 2, 1, 10, 2, 2, 3, 4, 12][i],
    buildingName: `지식·공장${i + 1}`,
    vatIncluded: true,
    region: i === 1 || i === 7 ? "홍성" : "내포신도시",
    eupmyeondong: i === 1 || i === 7 ? "홍성읍" : i === 3 || i === 5 ? "삽교읍" : "홍북읍",
    sigungu: i === 3 || i === 5 ? "예산군" : "홍성군",
    businessType: i < 5 ? "제조/물류" : "지식서비스",
    maintenanceFee: 30 + i * 3,
    specs: S({
      contractArea: 200 + i * 20,
      locationTrait: "기타",
      illegalBuilding: false,
      powerCapacityKw: 50 + i * 10,
      hvacType: i % 2 === 0 ? "천장형" : "없음",
      elevatorType: i % 3 === 0 ? "화물용" : "겸용",
      totalParking: 10 + i,
      freeParking: 5,
      toiletLocation: "내부",
    }),
  }),
);

const LANDS: PropertySeed[] = Array.from({ length: 10 }, (_, i) =>
  base({
    title: [
      "용봉 단독주택 부지 120평",
      "내포 택지 200평",
      "홍북 임야 500평",
      "삽교 계획관리 토지",
      "홍성 전·답 경작지",
      "내포 근생 가능 토지",
      "예산 나대지",
      "홍성 맹지 저가",
      "내포 도로접 평지",
      "홍북 과수원 지목",
    ][i],
    description: "토지/임야 네이버 규격 샘플. 지목·용도지역·도로접면 포함.",
    type: "SALE",
    category: "LAND",
    price: [85000, 120000, 45000, 98000, 32000, 150000, 70000, 18000, 135000, 55000][i],
    exclusiveArea: [396, 660, 1650, 520, 990, 430, 380, 280, 550, 720][i],
    landCategory: ["대", "대", "임야", "대", "전", "대", "대", "잡종지", "대", "과수원"][i],
    zoning: [
      "계획관리지역",
      "제2종일반주거지역",
      "농림지역",
      "계획관리지역",
      "농림지역",
      "근린상업지역",
      "계획관리지역",
      "생산관리지역",
      "제1종일반주거지역",
      "생산녹지지역",
    ][i],
    region: [0, 4, 7].includes(i) ? "홍성" : "내포신도시",
    eupmyeondong: [0, 4, 7].includes(i) ? "홍성읍" : [3, 6].includes(i) ? "삽교읍" : "홍북읍",
    sigungu: [3, 6].includes(i) ? "예산군" : "홍성군",
    tags: S(i === 7 ? ["급매"] : i === 1 ? ["택지"] : []),
    featured: i === 1,
    specs: S({
      roadAccess: ["4m 접", "8m 이상", "2m 미만", "6m 접", "4m 접", "8m 이상", "4m 접", "맹지", "8m 이상", "4m 접"][i],
      roadPaved: i === 7 || i === 2 ? "비포장" : "포장",
      terrain: ["평지", "평지", "완경사", "평지", "평지", "평지", "평지", "급경사", "평지", "완경사"][i],
      landShape: ["정방형", "정방형", "부정형", "세장형", "부정형", "정방형", "자루형", "부정형", "정방형", "부정형"][i],
      landUseStatus: ["나대지", "나대지", "임야", "나대지", "전·답 경작 중", "나대지", "나대지", "나대지", "나대지", "기타"][i],
    }),
  }),
);

export const PROPERTY_SEED_DATA: PropertySeed[] = [
  ...APARTMENTS,
  ...OFFICETELS,
  ...RETAILS,
  ...OFFICES,
  ...ROW_HOUSES,
  ...MULTI_FAMILY,
  ...DETACHED,
  ...ONE_ROOMS,
  ...FACTORIES,
  ...LANDS,
].map((p) => ({
  ...p,
  title: suggestPropertyTitle({
    category: p.category,
    type: p.type,
    buildingName: p.buildingName,
    exclusiveArea: p.exclusiveArea,
  }),
}));
