import type { SeedCustomerSpec } from "@/lib/customers/types";

function daysFromNow(n: number) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

/** 샘플 시드 전화번호 — 중복 삽입 방지·초기화용 */
export const CUSTOMER_SEED_PHONES = [
  "010-1111-2201",
  "010-2222-3302",
  "010-3333-4403",
  "010-4444-5504",
  "010-5555-6605",
] as const;

/** 샘플 고객 5명 — 차트·임박 위젯이 바로 보이도록 구성 */
export const CUSTOMER_SEED_SPECS: SeedCustomerSpec[] = [
  {
    name: "김○○",
    phone: "010-1111-2201",
    email: "kim.demo@example.com",
    currentAddress: "충남 홍성군 홍북읍",
    primaryContactMethod: "visit",
    hasTraded: false,
    isSubscribed: true,
    pipelineStage: "touring",
    budgetRange: "현금 3억 + 대출 2억",
    needsLoan: true,
    purpose: "reside",
    moveUrgency: "high",
    moveDate: daysFromNow(18),
    familyMembers: "부부 + 초등 자녀 1",
    preferredBrand: "센트럴자이 · 로얄층",
    decisionMaker: "배우자(아내) 최종 결정",
    inquiryDetails: "홍북읍 84㎡ 매매, 학군·주차 중요",
    requestNotes: "이사 일정 맞춰 잔금 조율 필요",
    specialNotes: "주말 오후에만 현장 가능",
    interactions: [
      {
        channel: "visit",
        title: "방문상담",
        body: "홍성읍·홍북 아파트 문의",
        daysAgo: 8,
      },
      {
        channel: "tour",
        title: "현장 투어",
        body: "센트럴자이 101동 투어 완료",
        daysAgo: 3,
      },
    ],
  },
  {
    name: "이○○",
    phone: "010-2222-3302",
    email: "lee.demo@example.com",
    currentAddress: "대전 유성구",
    primaryContactMethod: "phone",
    hasTraded: true,
    isSubscribed: false,
    pipelineStage: "contracting",
    budgetRange: "가용 5억 (대출 없음)",
    needsLoan: false,
    purpose: "invest",
    moveUrgency: "mid",
    moveDate: daysFromNow(45),
    familyMembers: "본인",
    preferredBrand: "내포 택지·수익형",
    decisionMaker: "본인",
    inquiryDetails: "갭투자 가능한 소형 아파트·상가",
    requestNotes: "수익률 4% 이상 희망",
    specialNotes: "기존 거래 고객(2024 전세)",
    interactions: [
      {
        channel: "phone",
        title: "전화상담",
        body: "내포 소형 매매 시세 문의",
        daysAgo: 5,
      },
    ],
  },
  {
    name: "박○○",
    phone: "010-3333-4403",
    email: null,
    currentAddress: "충남 예산군",
    primaryContactMethod: "web",
    hasTraded: false,
    isSubscribed: true,
    pipelineStage: "new",
    budgetRange: "전세 2.5억",
    needsLoan: false,
    purpose: "reside",
    moveUrgency: "low",
    moveDate: daysFromNow(90),
    familyMembers: "부부",
    preferredBrand: null,
    decisionMaker: "공동",
    inquiryDetails: "웹사이트 통해 전세 문의",
    requestNotes: "좋은 물건 나오면 천천히",
    specialNotes: "맞춤알림 신청 연계 검토",
    interactions: [
      {
        channel: "web",
        title: "웹 문의",
        body: "예산·홍성 전세 조건 문의",
        daysAgo: 1,
      },
    ],
  },
  {
    name: "최○○",
    phone: "010-4444-5504",
    email: "choi.demo@example.com",
    currentAddress: "서울 송파구 (지방 이주 검토)",
    primaryContactMethod: "email",
    hasTraded: false,
    isSubscribed: false,
    pipelineStage: "touring",
    budgetRange: "매매 4억대",
    needsLoan: true,
    purpose: "reside",
    moveUrgency: "high",
    moveDate: daysFromNow(12),
    familyMembers: "부부 + 중학생 1",
    preferredBrand: "반도유보라",
    decisionMaker: "본인",
    inquiryDetails: "학군·일조 좋은 중형 아파트",
    requestNotes: "한 달 내 계약 희망",
    specialNotes: "메일로 물건지 요약 요청",
    interactions: [
      {
        channel: "email",
        title: "메일상담",
        body: "후보 매물 3건 자료 송부",
        daysAgo: 4,
      },
      {
        channel: "phone",
        title: "전화 팔로업",
        body: "투어 일정 조율",
        daysAgo: 2,
      },
    ],
  },
  {
    name: "정○○",
    phone: "010-5555-6605",
    email: "jung.demo@example.com",
    currentAddress: "충남 서산시",
    primaryContactMethod: "phone",
    hasTraded: true,
    isSubscribed: true,
    pipelineStage: "dormant",
    budgetRange: "경매 감정가 대비 낙찰가 관심",
    needsLoan: true,
    purpose: "invest",
    moveUrgency: "low",
    moveDate: null,
    familyMembers: "본인",
    preferredBrand: null,
    decisionMaker: "본인",
    inquiryDetails: "경매 권리분석 상담 이력",
    requestNotes: "급매·경매만 알림",
    specialNotes: "최근 3개월 연락 없음",
    interactions: [
      {
        channel: "phone",
        title: "전화상담",
        body: "홍북 경매 물건 권리분석",
        daysAgo: 40,
      },
    ],
  },
];
